config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'subjects#welcome'
  
  get "/welcome" => "subjects#welcome"

  resources :subjects
  resources :users
  resources :roles

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/subject.rb
class Subject < ApplicationRecord
	enum status: ["New", "Old"]
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :username, presence: true
	belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
	
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	private
	def user_not_authorized
		flash[:alert] = "You are not authorized to perform this action."
		redirect_to(welcome_path)
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :username, :role_id)}
		devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :username, :role_id)}
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_action :set_role, only: [:show, :edit, :update, :destroy]

	def index
		@roles = Role.all
		authorize @roles
	end

	def show
		authorize @role
	end

	def new
		@role = Role.new
		authorize @role
	end

	def edit
		authorize @role
	end

	def create
		@role = Role.new(role_params)
		authorize @role
		if @role.save
			redirect_to @role, notice: 'Role was successfully created.'
		else
			render :new
		end
	end

	def update
		if @role.update(role_params)
			redirect_to @role, notice: 'Role was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		@role.destroy
		redirect_to roles_url, notice: 'Role was successfully destroyed.'
	end

	private 

	def set_role
		@role = Role.find(params[:id])
	end

	def role_params
		params.require(:role).permit(:name, :is_admin, :can_create, :can_read, :can_update, :can_delete)
	end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	before_action :set_subject, only: [:show, :edit, :update, :destroy]

	def index
		@subjects = Subject.all
		authorize @subjects
	end

	def welcome
	end

	def show
		authorize @subject
	end

	def new
		@subject = Subject.new
		authorize @subject
	end

	def edit
		authorize @subject
	end

	def create
		@subject = Subject.new(subject_params)
		authorize @subject
		if @subject.save
			redirect_to @subject, notice: 'Subject was successfully created.'
		else
			render :new
		end
	end

	def update
		authorize @subject
		if @subject.update(subject_params)
			redirect_to @subject, notice: 'Subject was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		authorize @subject
		@subject.destroy
		redirect_to subjects_url, notice: 'Subject was successfully destroyed.'
	end

	private 

	def set_subject
		@subject = Subject.find(params[:id])
	end

	def subject_params
		params.require(:subject).permit(:topic, :description, :status)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :authorize_user, except: [:index]

	def index
		@users = User.all
		authorize @users
	end

	def show
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: 'User was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to users_url, notice: 'User was successfully destroyed.'
	end

	private

	def authorize_user
		authorize @user
	end

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:username, :email, :role_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task12</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/subjects">Subjects</a>
          </li>
          <% if policy(:role).index? %>
            <li class="nav-item">          
              <a class="nav-link" href="/roles">Roles management</a>
            </li>
          <% end %>
          <% if policy(:user).index? %>
            <li class="nav-item">
              <a class="nav-link" href="/users">Users list</a>
            </li>
          <% end %>
        </ul>
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.username %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </nav>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= simple_form_for @role do |f|%>
	<%= f.input :name, label: 'Enter role name' %>
	<%= f.input :is_admin, as: :select, collection: [["Yes", true],["No", false]], label: "Is user admin?", include_blank: false %>
	<%= f.input :can_read, as: :select, collection: [["Yes", true],["No", false]], label: "Can user read subjects?", include_blank: false %>
	<%= f.input :can_create, as: :select, collection: [["Yes", true],["No", false]], label: "Can user create subjects?", include_blank: false %>
	<%= f.input :can_update, as: :select, collection: [["Yes", true],["No", false]], label: "Can user edit subjects?", include_blank: false %>
	<%= f.input :can_delete, as: :select, collection: [["Yes", true],["No", false]], label: "Can user delete subjects?", include_blank: false %>
	<%= f.button :submit %>
<% end %>

app/views/roles/edit.html.erb
<div class="container">
	<h1>Edit role</h1>
	<%= render 'form', role: @role %>
	<%= link_to 'Back', roles_path %>
</div>

app/views/roles/index.html.erb
<div class="container">
	<h1>Roles list</h1>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">Role</th>
				<th scope="col">Admin</th>
				<th scope="col">Read</th>
				<th scope="col">Create</th>
				<th scope="col">Update</th>
				<th scope="col">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @roles.each do |role| %>
				<tr>
					<th><%= link_to "#{role.name}", role_path(role) %></th>
					<th><%= role.is_admin %></th>
					<th><%= role.can_read %></th>
					<th><%= role.can_create %></th>
					<th><%= role.can_update %></th>
					<th><%= role.can_delete %></th>
				</tr>
			<% end %>
		</tbody>
	</table>

	<br><%= link_to 'New Role', new_role_path %>
</div>

app/views/roles/new.html.erb
<div class="container">
	<h1>Create role</h1>
	<%= render 'form', role: @role %>
	<%= link_to 'Back', roles_path %>
</div>

app/views/roles/show.html.erb
<div class="container">
	<h1>Role</h1>
	<h2><%= @role.name %></h2>

	Admin: <%= @role.is_admin %></br>
	Can view subjects: <%= @role.can_read %></br>
	Can create subjects: <%= @role.can_create %></br>
	Can edit subjects: <%= @role.can_update %></br>
	Can delete subjects: <%= @role.can_delete %></br>
</br>
	<%= link_to 'Edit role', edit_role_path(@role) %></br>
	<%= link_to 'Delete role', @role, method: :delete, data: { confirm: 'Are you sure?' } %></br>
	<%= link_to 'Back', roles_path %></br>
</div>	

app/views/subjects/_form.html.erb
<%= simple_form_for @subject do |f|%>
	<%= f.input :topic, label: 'Enter topic' %>
	<%= f.input :description, as: :text %>
	<%= f.button :submit %>
<% end %>

app/views/subjects/edit.html.erb
<div class="container">
	<h1>Edit subject</h1>
	<%= render 'form', subject: @subject %>
	<%= link_to 'Back', subjects_path %>
</div>

app/views/subjects/index.html.erb
<div class="container">
	<h1>Subjects list</h1>
	
	<% if policy(:subject).new? %>
		<br><%= link_to 'New Subject', new_subject_path %>
	<% end %>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">Topic</th>
				<th scope="col">Created at</th>
			</tr>
		</thead>
		<tbody>
			<% @subjects.each do |subject| %>
				<tr>
					<th><%= link_to "#{subject.topic}", subject_path(subject) %></th>
					<th><%= subject.created_at %></th>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/subjects/new.html.erb
<div class="container">
	<h1>New subject</h1>
	<%= render 'form', subject: @subject %>
	<%= link_to 'Back', subjects_path %>
</div>

app/views/subjects/show.html.erb
<div class="container">
	<h1><%= @subject.topic %></h1>

	<p><%= @subject.description %></p>
	<% if policy(:subject).edit? %>
		<%= link_to 'Edit subject', edit_subject_path(@subject) %></br>	
	<% end %>	
	<% if policy(:subject).destroy? %>
		<%= link_to 'Delete subject', @subject, method: :delete, data: { confirm: 'Are you sure?' } %></br>
	<% end %>
	<%= link_to 'Back', subjects_path %>
</div>

app/views/subjects/welcome.html.erb
<div class="container">
	<h1>Welcome to subjects app</h1>

	<h2>If you do not have accesss to other pages please <a href = "/users/sign_in">sign in</a> or <a href="/users/sign_up">create new account</a>. At first you can only read subjects. If you want to work with subjects, please wait until admin will manage your role.</h2>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f|%>
	<%= f.association :role, collection: Role.all, value_method: :id, include_blank: false %>
	<%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit user role</h1>
	<%= render 'form', user: @user %>
	<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h3>List of all users</h3>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">Username</th>
				<th scope="col">Role</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<th><%= link_to "#{user.username}", user_path(user) %></th>
					<th><%= user.role.name %></th>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/show.html.erb
<div class="container">
	Username: <%= @user.username %><br>
	Email: <%= @user.email %><br>
	Role: <%= link_to "#{@user.role.name}", role_path(@user.role)%><br>
	<%= link_to 'Edit user role', edit_user_path(@user) %><br>
	<%= link_to 'Delete user', @user, method: :delete, data: { confirm: 'Are you sure?' } %><br>
	<%= link_to 'Back', users_path %>
</div>